version: "3.9"

services:
  db:
    image: postgres:latest

    environment:
      - POSTGRES_PASSWORD=mezfi4-bafgoz-rysPom
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storeApi

    ports:
      - "5435:5432"

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - .:/frontend/app/frontend
      - /frontend/app/frontend/node_modules

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=mezfi4-bafgoz-rysPom
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storeApi
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db

networks:
  backend:
    driver: bridge
