# Generated by Django 4.2.11 on 2024-04-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_company_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_image',
        ),
    ]
