# Generated by Django 4.2.10 on 2024-02-29 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
